apiVersion: 1

datasources:
  - name: CommerceServing
    uid: commerce-pg
    type: postgres
    access: proxy
    url: postgres:5432
    user: grafana
    jsonData:
      database: serving
      sslmode: disable
      postgresVersion: 1600
    secureJsonData:
      password: grafana
    isDefault: true
    editable: false
